### ISSUE TITLE
Disable Update Checking

### ISSUE THREAD

**Issue by test137E29B** [TheTadeSK/QuickBoard#4]
Please add an option to disable checking for updates, or disable logging of checking if a new version is not found. I do not wish for my server console to be filled with the following every 30 minutes for no reason.
> [13:04:45 INFO]: Trying to get new version of QuickBoard...
> [13:04:45 INFO]: Current QuickBoard version: 4.2.1
> [13:04:45 INFO]: Web QuickBoard version: 4.2.1

Thank you

**Comment by tadeas-drab** [comment]
Fixed. Update message removed
